language: python
python:
  - "3.7"

services:
  - docker

addons:
  apt:
    packages:
    - libgdal-dev
    - libnetcdf-dev

before_script: pip install docker-compose

script: 
  - docker-compose run app sh -c "python manage.py test"