# Generated by Django 3.1.6 on 2021-02-15 12:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FAMILY', 'FAMILY'), ('FRIEND', 'FRIEND'), ('COLLEAGUE', 'COLLEAGUE'), ('ACQUAINTANCE', 'ACQUAINTANCE'), ('POI', 'POI')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_met', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pip')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('note_title', models.CharField(max_length=400)),
                ('note_content', models.TextField(blank=True, max_length=20000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_owner', to=settings.AUTH_USER_MODEL)),
                ('pip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pip')),
            ],
        ),
    ]
