# Generated by Django 3.1.6 on 2021-02-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210215_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pip_notes', to='core.pip'),
        ),
    ]
