# Generated by Django 3.1.7 on 2021-02-19 18:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.pipl_image_file_path),
        ),
    ]
